force-app/main/default/objects/Paypal__c/Paypal__c.object-meta.xml
<CustomObject>
    <label>Paypal</label>
    <nameField>
        <label>Paypal Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>PayPal</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Paypal__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>unpaid</fullName>
                <default>true</default>
                <label>unpaid</label>
            </value>
            <value>
                <fullName>paid</fullName>
            </value>
            <value>
                <fullName>claimed</fullName>
            </value>
            <value>
                <fullName>Unclaimed</fullName>
            </value>
            <value>
                <fullName>sent</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/approvedPaypalController.cls
/* * Author : S.Anand
   * CreatedDate : 12/11/2017
   * Version :1.0
   * Requirement: Implement Payment GateWay using Salesforce
*/

public class approvedPaypalController {

    public approvedPaypalController() {
        payPalApproved();
    }

    public List<Paypal__c> paypalApprovedList { get; set; }

    public void payPalApproved() {
        paypalApprovedList = new List<Paypal__c>();
        paypalApprovedList = [SELECT id, email__c,amount__c, status__c FROM Paypal__c LIMIT 250 FOR UPDATE];
    }
    
    public void pay() {
        // This is the killer method call:
        if(makePayment())
        {
            for(Paypal__c pp: paypalApprovedList)
            {
                if(pp.status__c == 'Unpaid') {
                    pp.status__c = 'Sent';
                }
            }
            update(paypalApprovedList);
        }  
    }
    
    public boolean makePayment() {
        PaypalProcessor p = new PaypalProcessor();
        boolean payResult;
        if(Test.isRunningTest())
        {
            payResult= true;    
        }
        else
        {
            payResult = p.processNewPayments();
        }
        if(payResult)
        {
            apexpages.addMessage(new ApexPages.Message(ApexPages.Severity.CONFIRM, 'Success'));
            return true;
        }
        else
        {
            apexpages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, 'Failure'));
            return false;
        }
    }

}