force-app/main/default/objects/Opportunity/fields/Opportunity_Type__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Type__c</fullName>
    <label>Opportunity Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>OEP</fullName>
            </value>
            <value>
                <fullName>SEP</fullName>
            </value>
            <value>
                <fullName>Dental/Vision</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/QLE_Type__c.field-meta.xml
<CustomField>
    <fullName>QLE_Type__c</fullName>
    <label>QLE Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Adoption</fullName>
            </value>
            <value>
                <fullName>Marriage</fullName>
            </value>
            <value>
                <fullName>Lost Coverage</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/TestPickList.cls
public class TestPickList {

@AuraEnabled
     public Static List<String> getPickListValues(){
          List<String> pickListValuesList= new List<String>();
        List<String> pickMap = new List<String> () ;
              List<String> pickMap1= new List<String>()  ;
        List<String> strList = new list<String>{'QLE_Type__c','Opportunity_Type__c'};
 Schema.DescribeFieldResult  fieldResult = Opportunity.QLE_Type__c.getDescribe();
            
                    List<Schema.PicklistEntry> ple = fieldResult.getPicklistValues();
		 System.debug('Map===>'+pickMap);
                for( Schema.PicklistEntry pickListVal : ple){
           System.debug('puickMap===>'+pickMap);
                         pickListValuesList.add(String.valueOf(pickListVal.getValue()));
            }
		return pickListValuesList;
     } 
@AuraEnabled
     public Static List<String> getPickListValues1(){
          List<String> pickListValuesList1= new List<String>();
        List<String> pickMap = new List<String> () ;
              List<String> pickMap1= new List<String>()  ;
        List<String> strList = new list<String>{'QLE_Type__c','Opportunity_Type__c'};
 Schema.DescribeFieldResult  fieldResult = Opportunity.Opportunity_Type__c.getDescribe();
            
                    List<Schema.PicklistEntry> ple = fieldResult.getPicklistValues();
		 System.debug('Map===>'+pickMap);
                for( Schema.PicklistEntry pickListVal : ple){
           System.debug('puickMap===>'+pickMap);
                         pickListValuesList1.add(String.valueOf(pickListVal.getValue()));
            }
		return pickListValuesList1;
     } 
         
    
}