force-app/main/default/objects/Patient__c/Patient__c.object-meta.xml
<CustomObject>
    <label>Patient</label>
    <nameField>
        <label>Pat Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Patient</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Patient__c/fields/CaseType__c.field-meta.xml
<CustomField>
    <fullName>CaseType__c</fullName>
    <label>CaseType</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Prescription__c/Prescription__c.object-meta.xml
<CustomObject>
    <label>Prescription</label>
    <nameField>
        <label>Prescription Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Prescription</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Prescription__c/fields/Dose__c.field-meta.xml
<CustomField>
    <fullName>Dose__c</fullName>
    <label>Dose</label>
    <length>120</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Prescription__c/fields/Patient__c.field-meta.xml
<CustomField>
    <fullName>Patient__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Patient</label>
    <referenceTo>Patient__c</referenceTo>
    <relationshipLabel>Prescription</relationshipLabel>
    <relationshipName>Prescription</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Revisit__c/Revisit__c.object-meta.xml
<CustomObject>
    <label>Revisit</label>
    <nameField>
        <label>Revisit Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Revisit</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Revisit__c/fields/Patient__c.field-meta.xml
<CustomField>
    <fullName>Patient__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Patient</label>
    <referenceTo>Patient__c</referenceTo>
    <relationshipLabel>Revisit</relationshipLabel>
    <relationshipName>Revisit</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/Hospital_Tabs.cls
public class Hospital_Tabs {
    private String selectedTab;
    Public  Patient__c   patient{set;get;}
    Public  prescription__c   prescription{set;get;}
    Public  Revisit__c   Revisit{set;get;}
    public String patientName {set;get;}
    public String caseType {set;get;}
    public String drug {set;get;}
    public String dose {set;get;}
    public String appointment {set;get;}
    public Hospital_Tabs(){
        selectedtab='Patient';
    }
    public Boolean getdisabledTab1(){
        return selectedTab !='Patient';
    }
    public Boolean getdisabledTab2(){
      return selectedTab != 'prescription';
    }
    public Boolean getdisabledTab3(){
      return selectedTab !='Revisit';
    }
    public void enableTab1(){
        selectedTab='Patient';
    }
    
    public void enableTab2(){
        selectedTab='Prescription';
    }
    
    public void enableTab3(){
        selectedTab='Revisit';
    }
    public String getselectedTab(){
        return selectedTab;
    }
    public PageReference save(){
        patient=new Patient__c();
        patient.name=patientName;
        patient.caseType__c=caseType;
        insert patient;
        prescription=new prescription__c();
        prescription.Name='xyz';
        prescription.Dose__c=Dose;
        prescription.patient__c=patient.Id;
        insert prescription;
        revisit=new Revisit__c();
        revisit.name='pqr';
        revisit.patient__c=patient.Id;
        insert revisit;
        pagereference pr = new pagereference('/' + patient.id);
        return pr;
    }
}