force-app/main/default/objects/Contact/fields/password__c.field-meta.xml
<CustomField>
    <fullName>password__c</fullName>
    <label>password</label>
    <length>16</length>
    <maskChar>asterisk</maskChar>
    <maskType>all</maskType>
    <type>EncryptedText</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Resettted__c.field-meta.xml
<CustomField>
    <fullName>Resettted__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Resetted</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/username__c.field-meta.xml
<CustomField>
    <fullName>username__c</fullName>
    <label>username</label>
    <length>12</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ResetPassword.cls
public class ResetPassword {
    public string username{set;get;}
    public string newPassword{set;get;}
    public string reenterPassword{set;get;}
    public void save(){
      contact con=[select username__c,password__c,Resettted__c from contact where username__c=:username];
        if(con.password__c=='Reset'){
         System.debug('eee');
            if(newPassword==reenterPassword){
                     System.debug('rrrrr');
                con.Resettted__c=false;
                con.password__c=newPassword;
                update con;
                ApexPages.addmessage(new ApexPages.message(ApexPages.severity.CONFIRM,'Password changed successfully'));
            }
            else{
                     System.debug('ccccccc');
             ApexPages.addmessage(new ApexPages.message(ApexPages.severity.INFO,'Passwords need to be matched'));
            }
        }
        else{
                 System.debug('qqqqqqqqqqq');
             ApexPages.addmessage(new ApexPages.message(ApexPages.severity.ERROR,'No permission to reset password'));
        }
    }
}