force-app/main/default/objects/InvoiceLineItems__c/InvoiceLineItems__c.object-meta.xml
<CustomObject>
    <label>InvoiceLineItems</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>InvoiceLineItems</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/InvoiceLineItems__c/fields/Invoice__c.field-meta.xml
<CustomField>
    <fullName>Invoice__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>InvoiceNo</label>
    <referenceTo>Invoiceno__c</referenceTo>
    <relationshipLabel>InvoiceLineItems</relationshipLabel>
    <relationshipName>InvoiceLineItems</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Invoiceno__c/Invoiceno__c.object-meta.xml
<CustomObject>
    <label>InvoiceNo</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Invoiceno</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>InvoiceNo</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/classes/Invoice_InvoiceLineItems.cls
/* Author:S.Anand
* Version:40.0
* Requirement:contains multiple triggers in form of methods
* CreatedDate:30/10/2017
*/


public class Invoice_InvoiceLineItems {
    // when ever new Invoice line item is created change ownership to invoice owner
    public static void afterInsert(List<InvoiceLineItems__c> invoiceItemsList){
        //Query the invoice id from invoiceLineitems
        invoiceItemsList=[select id,ownerid,Invoice__r.ownerid from InvoiceLIneItems__c];
        List<InvoiceLineItems__c> invoiceList = new List<InvoiceLineItems__c>();
        // change the owner id to invoice ownerid
        for(InvoiceLineItems__c lineItems:invoiceItemsList){
            system.debug('beforeId'+lineItems.OwnerId);
            lineItems.OwnerId=lineItems.Invoice__r.ownerid;
            system.debug('afterId'+lineItems.OwnerId);
            invoiceList.add(LineItems);
        } 
    update invoiceList;
    }
    
}