force-app/main/default/objects/Payment__c/Payment__c.object-meta.xml
<CustomObject>
    <label>Payment</label>
    <nameField>
        <label>Payment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Payments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Payment__c/fields/ConsumerKey__c.field-meta.xml
<CustomField>
    <fullName>ConsumerKey__c</fullName>
    <label>ConsumerKey</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Payment__c/fields/consumerSecret__c.field-meta.xml
<CustomField>
    <fullName>consumerSecret__c</fullName>
    <label>consumerSecret</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/Payment_Gateway_Gopay.cls
public class Payment_Gateway_Gopay {
 public String result{set;get;}
    public Payment_Gateway_Gopay(){
        Http p=new Http();
        payment__c pay=[select consumerSecret__c,ConsumerKey__c from payment__c where name=:'gopay'];
        HttpRequest request =new HttpRequest();
        request.setEndPoint('https://gw.sandbox.gopay.com/api');
        request.setMethod('POST');
        String body='grant_type=client_credentials';
        body=body+'&scope=payment-all';
      //  body=body+'&client_id='+pay.consumerSecret__c;
      //  body=body+'&client_secret='+pay.consumerkey__c;
        request.setBody(body);
        System.debug(body);
        HttpResponse response=p.send(request);
        result=response.getBody();
System.debug(result);
}

}